<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="colours.xacro"/>
	<xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="0.3"/> 
    <xacro:property name="chassis_width" value="0.2"/>
    <xacro:property name="chassis_height" value="0.11"/>
    <xacro:property name="chassis_mass" value="1.0"/>
	<xacro:property name="chassis_origin_x" value="${(chassis_length/2) + 0.005}"/>
	<xacro:property name="chassis_origin_y" value="0.0"/>
	<xacro:property name="chassis_origin_z" value="${(chassis_height/2 + wheel_radius)}"/>


    <xacro:property name="wheel_radius" value="0.03"/>
    <xacro:property name="wheel_thickness" value="0.015"/>
    <xacro:property name="wheel_mass" value="0.05"/>
	<xacro:property name="wheel_origin_x" value="0.0"/>
	<xacro:property name="wheel_origin_y" value="${(chassis_width/2) + (wheel_thickness/2) + 0.01}"/>
	<xacro:property name="wheel_origin_z" value="${chassis_height/2}"/>


    <xacro:property name="caster_wheel_radius" value="${wheel_radius}"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
	<xacro:property name="caster_wheel_origin_x" value="${(chassis_length/2)-caster_wheel_radius}"/>
	<xacro:property name="caster_wheel_origin_y" value="0.0"/>
	<xacro:property name="caster_wheel_origin_z" value="${wheel_origin_z}"/>

	<xacro:property name="mu" value="0.001"/>


<!-- BASE LINK-->
	<link name="base_link">

	</link>

	<joint name="chassis_joint" type="fixed">
		<parent link="base_link"/>
		<child link="chassis"/>
		<origin xyz="${chassis_origin_x} ${chassis_origin_y} ${chassis_origin_z}"/>
	</joint>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


<!-- CHASSIS-->
	<link name="chassis">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
			</geometry>
			<material name="orange"/>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
			</geometry>
		</collision>

		<xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_box>

	</link>

	<gazebo reference="chassis">
		<material>Gazebo/Orange</material>
	</gazebo>

<!-- LEFT WHEEL-->
	<joint name="left_wheel_joint" type="continuous">
		<parent link="chassis"/>
		<child link="left_wheel"/>
		<origin xyz="${wheel_origin_x} ${wheel_origin_y} -${wheel_origin_z}" rpy="-${pi/2} 0 0"/>
		<axis xyz="0 0 1"/>
	</joint>

	<link name="left_wheel">
		<visual>
			<geometry>
				<cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
			</geometry>
			<material name="blue"/>
		</visual>

		<collision>
			<geometry>
				<sphere radius="${wheel_radius}"/>
			</geometry>
		</collision>

		<xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
			<origin xyz= "0 0 0" rpy="0 0 0"/>
		</xacro:inertial_cylinder>
	</link>

	<gazebo reference="left_wheel">
		<material>Gazebo/Blue</material>
	</gazebo>

<!-- RIGHT WHEEL-->
	<joint name="right_wheel_joint" type="continuous">
		<parent link="chassis"/>
		<child link="right_wheel"/>
		<origin xyz="${wheel_origin_x} -${wheel_origin_y} -${wheel_origin_z}" rpy="${pi/2} 0 0"/>
		<axis xyz="0 0 -1"/>
	</joint>

	<link name="right_wheel">
		<visual>
			<geometry>
				<cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
			</geometry>
			<material name="blue"/>
		</visual>

		<collision>
			<geometry>
				<sphere radius="${wheel_radius}"/>
			</geometry>
		</collision>

		<xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_cylinder>
	</link>

	<gazebo reference="right_wheel">
		<material>Gazebo/Blue</material>
	</gazebo>

<!-- FRONT CASTER WHEEL-->
	<joint name="front_caster_wheel_joint" type="fixed">
		<parent link="chassis"/>
		<child link="front_caster_wheel"/>
		<origin xyz="${caster_wheel_origin_x} ${caster_wheel_origin_y} -${caster_wheel_origin_z}" rpy="0 0 0"/>
		<!-- <axis xyz="1 1 0"/> -->
	</joint>

	<link name="front_caster_wheel">
		<visual>
			<geometry>
				<sphere radius="${caster_wheel_radius}"/>
			</geometry>
			<material name="white"/>
		</visual>

		<collision>
			<geometry>
				<sphere radius="${caster_wheel_radius}"/>
			</geometry>
		</collision>

		<xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_sphere>
	</link>

	<gazebo reference="front_caster_wheel">
		<material>Gazebo/White</material>
		<mu1 value="${mu}"/>
		<mu2 value="${mu}"/>
	</gazebo>

<!-- BACK CASTER WHEEL-->
	<joint name="back_caster_wheel_joint" type="fixed">
		<parent link="chassis"/>
		<child link="back_caster_wheel"/>
		<origin xyz="-${caster_wheel_origin_x} ${caster_wheel_origin_y} -${caster_wheel_origin_z}" rpy="0 0 0"/>
		<!-- <axis xyz="1 1 0"/> -->
	</joint>

	<link name="back_caster_wheel">
		<visual>
			<geometry>
				<sphere radius="${caster_wheel_radius}"/>
			</geometry>
			<material name="white"/>
		</visual>

		<collision>
			<geometry>
				<sphere radius="${caster_wheel_radius}"/>
			</geometry>
		</collision>

		<xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_sphere>
	</link>

	<gazebo reference="back_caster_wheel">
		<material>Gazebo/White</material>
		<mu1 value="${mu}"/>
		<mu2 value="${mu}"/>
	</gazebo>	
	
</robot>
